# Generated by Django 3.0.5 on 2020-12-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201227_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag_name',
        ),
    ]
